---
# Indicate whether to verify gpg signatures during install
gpgcheck: 1

# Indicate whether to upgrade Ansible as well as Tower
upgrade_ansible_with_tower: false

# Specify the format to use when installing tower with the 'yum' module.
tower_package_rpm: '{{ packages_el_tower_package_name }} == {{ packages_el_tower_package_version }}'

awx_install_home: '/var/lib/awx'

# These need to be base packages only

el_dependencies: []
dnf_modules: []

el_obsolete:
  - rabbitmq-server

packages_el_install_tower: true
packages_el_install_postgres: false

ansible_tower_repo: ansible-tower
ansible_tower_dependency_repo: ansible-tower-dependencies
