---
- name: Ensure that tower job_status directory exists.
  file:
    group: "{{ aw_group }}"
    mode: 0755
    owner: "{{ aw_user }}"
    path: "{{ restore_awx_home }}/job_status"
    state: directory

- name: Restore job stdout
  shell: rsync -aq {{ backup_dir.rstrip("/") }}/restore/job_status/ {{ restore_awx_home }}/job_status/
  when: has_host_archive
