---
el_dependencies:
  - python-psycopg2
  - python-setuptools
  - libselinux-python
  - setools-libs
  - yum-utils
  - sudo
  - acl

postgresql_packages:
  - rh-postgresql10-postgresql-server
  - rh-postgresql10-postgresql-contrib

upgrade_postgres: False
extra_env:
  LD_LIBRARY_PATH: '/opt/rh/rh-postgresql10/root/usr/lib64'
