---

- include: vars.yml

- block:
    - name: ensure /var/run/memcached exists
      file: path=/var/run/memcached state=directory mode=0750 owner='{{ memcached_user }}' group='{{ memcached_user }}'

    - name: ensure /var/run/memcached has the correct SELinux context
      shell: restorecon -R /var/run/memcached

    - name: Create tmpfiles.d entry for memcached socket directory
      template:
        src: memcached.conf.j2
        dest: /etc/tmpfiles.d/memcached.conf
        force: yes
        mode: '0640'
        owner: root
        group: 'root'

    - name: bind memcached to a unix domain socket
      lineinfile:
        dest: /etc/sysconfig/memcached
        regexp: '^OPTIONS='
        line: 'OPTIONS="-s /var/run/memcached/memcached.sock -a 0660"'
      register: memcached_conf

    - name: restart memcached when bind settings changed
      service:
        name: memcached
        state: restarted
      when: memcached_conf is changed

    - name: add awx to the memcached group so it can access the socket
      user: name=awx groups='{{ memcached_user }}' append=yes
  when: awx_install_memcached_bind.startswith('unix:')

- name: Start Memcached and enable it at startup
  service:
    name: memcached
    state: started
    enabled: yes
